// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rknnyxjipmdlijasuphl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrbm55eGppcG1kbGlqYXN1cGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MjAwODksImV4cCI6MjA3NjM5NjA4OX0.RsuuWM5Tjv4wsXPoPhA2E1NGb9Jhl7X18jghepOIWY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});